





















function nina(){




//  let num1=prompt("enter the number 1") //"5"   string

//  let num2=prompt("enter the number 2 ") //"3"

//  let ans=num1+num2    //"5"+"3" =>"53"


//  alert (ans) // or (num1+num2)



////////parseInt int method


let num1=parseInt(prompt("enter the number 1"))  ///"5" =>5 number(parseInt())

let num2=parseInt(prompt("enter the number 2"))

let ans=num1+num2
alert (ans)
}


nina()